### ISSUE TITLE
Providing k-anonymity model for NTLM hashes?

### ISSUE THREAD

**Issue by IgorMilavec** [HaveIBeenPwned/PwnedPasswordsAzureFunction#86]
Any chance of providing k-anonymity ranges for NTLM hashes?
I think this would be valuable for checking local user's passwords in small AD domains, where downloading the whole corpus is a bit too much.

**Comment by stebet** [comment]
This is something that has been brought up before right? @troyhunt

**Comment by miztroh** [comment]
@stebet @troyhunt I sent an email about this yesterday.  Happy to track progress on this request here.  Thanks again!

**Comment by miztroh** [comment]
@stebet @troyhunt Any update here?  Unfortunately, I don't have the experience to look at adding in this functionality to this repo.  For now, I've taken the monolithic NTLM data from last December and ingested it into an indexed database.  I'm consuming that data with a Node.js server application that works identically to the k-anonymity API you're currently providing.  However, as this data continues to age, I'm much more interested in being able to query against the live dataset instead using NTLM hash prefixes.  Please let us know if this request can move forward and what an ETA might look like.  Thanks!

**Comment by stebet** [comment]
@miztroh I’ve been off on summer vacation lately but me and @troyhunt have discussed his briefly. We’ll go another round see what comes out of it :)

**Comment by miztroh** [comment]
@stebet Any update here?  Thanks!

**Comment by stebet** [comment]
This being worked on :). The downloader will be updated soon as well to support downloading the NTLM hashes.

**Comment by stebet** [comment]
Done and delivered! https://www.troyhunt.com/pwned-passwords-adds-ntlm-support-to-the-firehose/

**Comment by miztroh** [comment]
@stebet Thank you so much for your work on this.  It's a huge win for my team and I know it will be for others as well!

**Comment by gino840** [comment]
To download ntlm hashes is there a flag?

**Comment by stebet** [comment]
> To download ntlm hashes is there a flag?

Yes! Use `-n` to download the NTLM hashes.

**Comment by noobhands** [comment]
perfect, thank you very much!
